name: pyclass
channels:
  - conda-forge
dependencies:
  # required
  - python=3.9
  - pip

  - numpy
  - matplotlib

  - jupyter
  - jupytext
  - jupyterlab

  - python-dateutil
  - affine
  - scipy
  - openpyxl
  - xlrd
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - rasterstats
  - fiona
  - descartes
  - pyproj
  - shapely
  - geos
  - geojson
  - geopandas
  - vtk
  - xarray
  - pyyaml
  - rtree
  - requests
  - pytest
  - statsmodels
  - pygeohydro

  - pip:
      - gis-utils
      - git+https://github.com/modflowpy/flopy@develop
      - git+https://github.com/doi-usgs/sfrmaker@develop
      - git+https://github.com/doi-usgs/modflow-setup@develop
