name: pyclass
channels:
  - conda-forge
  - nodefaults
dependencies:
  # required
  - python=3.12
  - pip

  - numpy
  - matplotlib

  - jupyter
  - jupytext
  - jupyterlab
  - git
  - python-dateutil
  - affine
  - scipy
  - openpyxl
  - xlrd
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - rasterstats
  - fiona
  - descartes
  - pyproj
  - shapely
  - geos
  - geojson
  - geopandas
  - xarray
  - rioxarray
  - uxarray
  - pyyaml
  - rtree
  - pyvista
  - vtk
  - imageio
  - requests
  - pytest
  - statsmodels
  - dataretrieval
  - flopy>=3.7
  - gis-utils
  - sfrmaker
  - contextily
  - cartopy
  - modflow-export
  - modflow-setup
