name: pyclass
channels:
  - conda-forge
dependencies:
  # required
  - python=3.9
  - pip

  - numpy
  - matplotlib=3.4.3

  - jupyter
  - jupytext
  - jupyterlab
  - git
  - python-dateutil
  - affine
  - scipy
  - openpyxl
  - xlrd
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - rasterstats
  - fiona>=1.8.21
  - descartes
  - pyproj
  - shapely
  - geos
  - geojson
  - geopandas
  - vtk
  - xarray
  - pyyaml
  - rtree
  - requests
  - pytest
  - statsmodels
  - pygeohydro=0.13.6
  - pynhd
  - pydaymet
  - async-retriever
  - hydrofunctions

  - pip:
      - gis-utils
      - git+https://github.com/modflowpy/flopy@develop
      - git+https://github.com/doi-usgs/sfrmaker@develop
      - git+https://github.com/doi-usgs/modflow-setup@develop
      - utm
