name: pyclass
channels:
  - conda-forge
dependencies:
  # required
  - python=3.11
  - pip

  - numpy
  - matplotlib

  - jupyter
  - jupytext
  - jupyterlab
  - git
  - python-dateutil
  - affine
  - scipy
  - openpyxl
  - xlrd
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - rasterstats
  - fiona
  - descartes
  - pyproj
  - shapely
  - geos
  - geojson
  - geopandas
  - vtk
  - xarray
  - pyyaml
  - rtree
  - requests
  - pytest
  - statsmodels
  - dataretrieval
