name: pyclass-docs
channels:
  - conda-forge
dependencies:
  # required
  - python=3.11
  - pip

  - numpy
  - matplotlib

  - jupyter
  - jupytext
  - jupyterlab
  - git
  - python-dateutil
  - affine
  - scipy
  - openpyxl
  - xlrd
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - rasterstats
  - fiona
  - descartes
  - pyproj
  - shapely
  - geos
  - geojson
  - geopandas
  - vtk
  - xarray
  - rioxarray
  - uxarray
  - pyyaml
  - rtree
  - requests
  - pytest
  - statsmodels
  - dataretrieval
  - flopy
  - gis-utils
  - sfrmaker
  - modflow-export
  - modflow-setup
  - sphinx
  - numpydoc
  - nbsphinx  # for rendering notebooks in sphinx-generated docs
  - sphinx-copybutton
  - sphinx_rtd_theme
  - myst-parser  # for including markdown source
