# Based on github template: https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Tests

on:
  schedule:
    - cron: '0 9 * * 1' # run every Monday at 9 AM UTC (3 am PST)
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ['3.9']  # ['3.8', '3.x']

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Fetch all Git tags
      run: git fetch --prune --unshallow --tags

    - name: Cache Miniconda
      uses: actions/cache@v2.1.0
      env:
        # Increase this value to reset cache if environment.yml has changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-${{ matrix.python-version }}-${{
             matrix.run-type }}-${{ env.CACHE_NUMBER }}-${{
             hashFiles('ci/test_environment.yaml') }}

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: pyclass
        environment-file: installation/environment.yml
        #condarc-file: ci/example-condarc.yml
        auto-activate-base: false
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Install Modflow executables
      uses: modflowpy/install-modflow-action@v1
      with:
        path: ~/.local/bin
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Modflow version
      shell: bash -l {0}
      run: mf6 --version
    - name: Install ipykernel
      shell: bash -l {0}
      run: |
        python -m ipykernel install --user --name pyclass --display-name "pyclass"
    - name: Conda list
      shell: bash -l {0}
      run: conda list
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v
